### ISSUE TITLE
Humble release?

### ISSUE THREAD

**Issue by Minipada** [nobleo/magic_enum-release#1]
Hi,
Thanks for packaging this, is a Humble release planned? It would be great!

**Comment by Timple** [comment]
Sure: https://github.com/ros/rosdistro/pull/35321

**Comment by Minipada** [comment]
Wow that was fast. Thanks!

**Comment by kosuke55** [comment]
Thanks for the release.
I added `<depend>magic_enum</depend>` in my pacakge.xml and ran
`rosdep install -y --from-paths src --ignore-src --rosdistro humble`
but it showed `Cannot locate rosdep definition for [magic_enum]`.
Could you give me some advice?

**Comment by Timple** [comment]
Did you run `rosdep update` first?
Because here it simply returns 
```
$ rosdep resolve magic_enum
#apt
ros-humble-magic-enum
```

**Comment by kosuke55** [comment]
Thanks, I didn't run it. The problem is solved.
